"""Independent immutable anchors for the Task 1 architecture contracts."""

from __future__ import annotations

from types import MappingProxyType

BASELINE_COMMIT = "f9fd489806a86b3a56f62b8668aafa252012d405"

BASELINE_MODULE_AUTHORITIES = MappingProxyType(
    {
        "uquant": "production_safe",
        "uquant.__main__": "cli_runner",
        "uquant.account": "production_safe",
        "uquant.atomic_io": "production_safe",
        "uquant.attribution": "production_safe",
        "uquant.broker": "production_safe",
        "uquant.cli": "cli_runner",
        "uquant.config": "production_safe",
        "uquant.config_governance": "production_safe",
        "uquant.data": "production_safe",
        "uquant.engine": "production_safe",
        "uquant.execution": "production_safe",
        "uquant.execution_journal": "production_safe",
        "uquant.features": "production_safe",
        "uquant.industry": "production_safe",
        "uquant.leader": "production_safe",
        "uquant.market_risk": "production_safe",
        "uquant.opportunity": "production_safe",
        "uquant.portfolio": "production_safe",
        "uquant.portfolio_core": "production_safe",
        "uquant.portfolio_leaders": "production_safe",
        "uquant.portfolio_recovery": "production_safe",
        "uquant.portfolio_strategic": "production_safe",
        "uquant.reference": "production_safe",
        "uquant.reference_registry": "production_safe",
        "uquant.report": "production_safe",
        "uquant.risk": "production_safe",
        "uquant.risk_sector": "production_safe",
        "uquant.risk_sentinel": "production_safe",
        "uquant.risk_sentinel.__main__": "cli_runner",
        "uquant.risk_sentinel.calibration": "validation_runner",
        "uquant.risk_sentinel.cli": "cli_runner",
        "uquant.risk_sentinel.coverage": "production_safe",
        "uquant.risk_sentinel.evidence": "production_safe",
        "uquant.risk_sentinel.history": "production_safe",
        "uquant.risk_sentinel.integration": "production_safe",
        "uquant.risk_sentinel.models": "production_safe",
        "uquant.risk_sentinel.opinion": "production_safe",
        "uquant.risk_sentinel.service": "production_safe",
        "uquant.risk_sentinel.validation": "validation_runner",
        "uquant.types": "production_safe",
        "uquant.validation": "validation_runner",
        "uquant.validation.__main__": "cli_runner",
        "uquant.validation.ai_era": "production_safe",
        "uquant.validation.ci_artifacts": "cli_runner",
        "uquant.validation.cli": "cli_runner",
        "uquant.validation.competitor": "validation_runner",
        "uquant.validation.control_plane": "validation_runner",
        "uquant.validation.equivalence": "validation_runner",
        "uquant.validation.execution_journal": "validation_runner",
        "uquant.validation.generalization": "validation_runner",
        "uquant.validation.generalization_contract": "validation_runner",
        "uquant.validation.generalization_matrix": "validation_runner",
        "uquant.validation.generalization_reference": "validation_runner",
        "uquant.validation.holdout": "validation_runner",
        "uquant.validation.holdout_lanes": "validation_runner",
        "uquant.validation.holdout_runtime": "validation_runner",
        "uquant.validation.manifest": "validation_runner",
        "uquant.validation.promotion": "validation_runner",
        "uquant.validation.replay_evidence": "validation_runner",
        "uquant.validation.universe": "production_safe",
    }
)
