"""Compatibility facade for the frozen generalization reference policy."""

from __future__ import annotations

from .generalization_matrix import _head_and_source as _head_and_source
from .generalization_policy.cells import (
    _load_baseline_cells,
    load_generalization_baseline,
    load_generalization_policy,
)
from .generalization_policy.evaluator import (
    _evaluate_recovered_against_group_envelope,
    _quantile,
    _random_tail_statistics,
    _RandomTailStatistics,
    _violates_effective_floor,
    evaluate_cell_non_regression,
    evaluate_generalization_policy_artifact,
)
from .generalization_policy.projection import (
    _attribution_neutral_equality_sha256,
    _project_raw_evidence_for_frozen_v1,
    _v2_economic_projection,
)
from .generalization_policy.projection import (
    _candidate_contract_sha256 as _candidate_contract_sha256,
)
from .generalization_policy.schema import (
    _ADDITIVE_ATTRIBUTION_IDENTITY_FIELDS,
    _ARTIFACT_FIELDS_V1,
    _ARTIFACT_FIELDS_V2,
    _ATTRIBUTION_DEFINITION,
    _BASELINE_CELL_FIELDS,
    _CELL_FIELDS_V1,
    _CELL_FIELDS_V2,
    _COMMIT,
    _DATA_FIELDS,
    _DEPRECATED_V1_ATTRIBUTION_TOKEN,
    _EVIDENCE_FIELDS,
    _METRIC_FIELDS,
    _PROVENANCE_FIELDS,
    _REQUIRED_DEPRECATED_V1_ATTRIBUTION_COLLECTION_SHA256,
    _ROOT,
    _RUNTIME_FIELDS,
    _SHA256,
    CHAMPION_MATRIX_PATH,
    GENERALIZATION_BASELINE_PATH,
    GENERALIZATION_POLICY_PATH,
    REQUIRED_GENERALIZATION_BASELINE_SHA256,
    REQUIRED_GENERALIZATION_POLICY_SHA256,
    BaselineCell,
    GeneralizationBaseline,
    GeneralizationPolicy,
    ReplayError,
    _artifact_equality_sha256,
    _canonical_sha256,
    _derived_seed,
    _hash_json,
    _metric_payload,
    _metrics_reconciled_from_raw,
    _provenance_schema_failures,
    _read_json,
    _reject_duplicate_keys,
    _reject_nonstandard_constant,
    _replay_error,
    _require_exact_seal,
    _require_sha256,
    _schema_failures,
)

for _value in (
    ReplayError,
    BaselineCell,
    GeneralizationBaseline,
    GeneralizationPolicy,
    _reject_duplicate_keys,
    _reject_nonstandard_constant,
    _read_json,
    _hash_json,
    _artifact_equality_sha256,
    _schema_failures,
    _provenance_schema_failures,
    _metrics_reconciled_from_raw,
    _canonical_sha256,
    _require_sha256,
    _require_exact_seal,
    _metric_payload,
    _replay_error,
    _derived_seed,
    _load_baseline_cells,
    load_generalization_baseline,
    load_generalization_policy,
    evaluate_cell_non_regression,
    _evaluate_recovered_against_group_envelope,
    _quantile,
    _RandomTailStatistics,
    _random_tail_statistics,
    _violates_effective_floor,
    _candidate_contract_sha256,
    _project_raw_evidence_for_frozen_v1,
    _v2_economic_projection,
    _attribution_neutral_equality_sha256,
    evaluate_generalization_policy_artifact,
):
    _value.__module__ = __name__

__all__ = (  # noqa: RUF022 - frozen public-name order
    "BaselineCell",
    "CHAMPION_MATRIX_PATH",
    "GENERALIZATION_BASELINE_PATH",
    "GENERALIZATION_POLICY_PATH",
    "GeneralizationBaseline",
    "GeneralizationPolicy",
    "REQUIRED_GENERALIZATION_BASELINE_SHA256",
    "REQUIRED_GENERALIZATION_POLICY_SHA256",
    "ReplayError",
    "_ADDITIVE_ATTRIBUTION_IDENTITY_FIELDS",
    "_ARTIFACT_FIELDS_V1",
    "_ARTIFACT_FIELDS_V2",
    "_ATTRIBUTION_DEFINITION",
    "_BASELINE_CELL_FIELDS",
    "_CELL_FIELDS_V1",
    "_CELL_FIELDS_V2",
    "_COMMIT",
    "_DATA_FIELDS",
    "_DEPRECATED_V1_ATTRIBUTION_TOKEN",
    "_EVIDENCE_FIELDS",
    "_METRIC_FIELDS",
    "_PROVENANCE_FIELDS",
    "_REQUIRED_DEPRECATED_V1_ATTRIBUTION_COLLECTION_SHA256",
    "_ROOT",
    "_RUNTIME_FIELDS",
    "_SHA256",
    "evaluate_cell_non_regression",
    "evaluate_generalization_policy_artifact",
    "load_generalization_baseline",
    "load_generalization_policy",
)
