"""Compatibility re-export for the canonical domain-model package."""

# Relocated classes retain ``uquant.types`` identity, so runtime hint resolution
# needs the historical annotation name in this facade namespace.
from typing import Any as Any

from .models import (
    ACCOUNT_SCHEMA_VERSION,
    ATTRIBUTION_IDENTITY_FIELDS,
    ORDER_INTENT_IMMUTABLE_FIELDS,
    AccountOrder,
    AccountState,
    AttributionIdentity,
    AttributionMechanism,
    Decision,
    Fill,
    FlatBookCapitalRepairResetReason,
    FlatBookCapitalRepairState,
    FlatBookCapitalRepairStatus,
    LeaderScore,
    Lifecycle,
    Opportunity,
    OrderStatus,
    OriginSubsystem,
    PendingOrder,
    Position,
    ReductionPolicy,
    ReferenceAvailability,
    Risk,
    RiskAssessment,
    Side,
    StrategicCashRearmPredicate,
    StrategicCashRearmRejectionReason,
    StrategicCashRearmState,
    StrategicCashRearmStatus,
    StrategicCashRearmStreakTransition,
    StrategicEpoch,
    StrategicEpochStatus,
    StrategicGrantIntent,
    StrategicGrantStatus,
    StrategicQualificationObservation,
    StrategicRearmAuthorization,
    StrategicUniverseDeclaration,
    StrategicUniverseRoles,
    Target,
    Tranche,
    bind_account_strategic_ownership,
    build_strategic_universe_declaration,
    build_strategic_universe_roles,
    derive_attribution_event_id,
    derive_flat_book_capital_repair_episode_id,
    derive_strategic_cash_rearm_authorization_id,
    derive_strategic_epoch_id,
    derive_strategic_grant_id,
    order_intent_metadata,
    validate_attribution_compatibility,
)
from .models import trading as _trading

_ATTRIBUTION_COMPATIBILITY = _trading.ATTRIBUTION_COMPATIBILITY
del _trading

__all__ = (  # noqa: RUF022 - preserve the frozen compatibility export order
    "ACCOUNT_SCHEMA_VERSION",
    "ATTRIBUTION_IDENTITY_FIELDS",
    "AccountOrder",
    "AccountState",
    "AttributionIdentity",
    "AttributionMechanism",
    "Decision",
    "Fill",
    "FlatBookCapitalRepairResetReason",
    "FlatBookCapitalRepairState",
    "FlatBookCapitalRepairStatus",
    "LeaderScore",
    "Lifecycle",
    "ORDER_INTENT_IMMUTABLE_FIELDS",
    "Opportunity",
    "OrderStatus",
    "OriginSubsystem",
    "PendingOrder",
    "Position",
    "ReferenceAvailability",
    "ReductionPolicy",
    "Risk",
    "RiskAssessment",
    "Side",
    "StrategicEpoch",
    "StrategicEpochStatus",
    "StrategicCashRearmPredicate",
    "StrategicCashRearmRejectionReason",
    "StrategicCashRearmState",
    "StrategicCashRearmStatus",
    "StrategicCashRearmStreakTransition",
    "StrategicRearmAuthorization",
    "StrategicUniverseDeclaration",
    "StrategicUniverseRoles",
    "StrategicGrantIntent",
    "StrategicGrantStatus",
    "StrategicQualificationObservation",
    "Target",
    "Tranche",
    "_ATTRIBUTION_COMPATIBILITY",
    "bind_account_strategic_ownership",
    "build_strategic_universe_declaration",
    "build_strategic_universe_roles",
    "derive_attribution_event_id",
    "derive_flat_book_capital_repair_episode_id",
    "derive_strategic_epoch_id",
    "derive_strategic_cash_rearm_authorization_id",
    "derive_strategic_grant_id",
    "order_intent_metadata",
    "validate_attribution_compatibility",
)
