"""Centralize ordinary wire-state access and frozen observation commits."""
import json
import hashlib

write("uquant/models/ordinary_state.py", (ROOT/"artifacts/code-audit-fix/sources/ordinary_state.py").read_text())
replace('uquant/portfolio/pipeline.py', 'from ..models.strategic_universe import StrategicUniverseRoles\n', 'from ..models.ordinary_state import CoreTransfer, clear_repair_origins, repair_origin_recorded, transfers\nfrom ..models.strategic_universe import StrategicUniverseRoles\n', count=1)
replace('uquant/portfolio/pipeline.py', '    symbol = key.split(":", 1)[1].split("->", 1)[0]\n    signal = account.candidate_tenure.get(key.replace("core_transfer:", "core_transfer_session:", 1))', '    transfer = CoreTransfer.from_key(key)\n    symbol = transfer.incumbent\n    signal = transfer.observed_session(account)', count=1)
replace('uquant/portfolio/pipeline.py', '    key = f"core_transfer:{weakest}->{challenger}"\n    clock = f"core_transfer_session:{weakest}->{challenger}"\n    observed = date.toordinal()\n    previous = frame.loc[:date].index[-2].toordinal() if len(frame.loc[:date]) > 1 else 0\n    last_observed = account.candidate_tenure.get(clock, 0)\n    if last_observed > observed:\n        raise RuntimeError("transfer observation session moved backwards")\n    if (account.replacement_tenure.get(key, 0) >= self.cfg.replacement_confirm_days\n            and _transfer_sell_filled(account, key, date)):\n        return key\n    if last_observed != observed:\n        streak = account.replacement_tenure.get(key, 0) if last_observed == previous else 0\n        account.replacement_tenure[key] = streak + 1 if broken and edge >= self.cfg.replacement_edge else 0\n        account.candidate_tenure[clock] = observed\n    return key\n', '    transfer = CoreTransfer(weakest, challenger)\n    observed = date.toordinal()\n    previous = frame.loc[:date].index[-2].toordinal() if len(frame.loc[:date]) > 1 else 0\n    if transfer.observed_session(account) > observed:\n        raise RuntimeError("transfer observation session moved backwards")\n    if (transfer.confirmations(account) >= self.cfg.replacement_confirm_days\n            and _transfer_sell_filled(account, transfer.key, date)):\n        return transfer.key\n    transfer.observe(account, session=observed, previous_session=previous,\n                     qualified=broken and edge >= self.cfg.replacement_edge)\n    return transfer.key\n', count=1)
replace('uquant/portfolio/pipeline.py', 'account.replacement_tenure[key] < self.cfg.replacement_confirm_days', 'CoreTransfer.from_key(key).confirmations(account) < self.cfg.replacement_confirm_days', count=1)
replace('uquant/portfolio/pipeline.py', '    account.candidate_tenure[key.replace("core_transfer:", "core_transfer_session:", 1)] = date.toordinal()\n    for observed in account.replacement_tenure:\n        if observed.startswith("core_transfer:") and observed != key:\n            account.replacement_tenure[observed] = 0', '    CoreTransfer.from_key(key).record_request(account, date.toordinal())', count=1)
replace('uquant/portfolio/pipeline.py', '    transfers = [key for key, tenure in book.account.replacement_tenure.items()\n                 if key.startswith("core_transfer:") and key.endswith("->" + symbol)\n                 and tenure >= book.policy.cfg.replacement_confirm_days\n                 and _transfer_sell_filled(book.account, key, book.date)]\n    if transfers:\n        transfer = sorted(transfers)[0]\n        book.replacements[symbol] = transfer.split(":", 1)[1].split("->", 1)[0]', '    completed = [item for item in transfers(book.account)\n                 if item.challenger == symbol\n                 and item.confirmations(book.account) >= book.policy.cfg.replacement_confirm_days\n                 and _transfer_sell_filled(book.account, item.key, book.date)]\n    if completed:\n        transfer = min(completed, key=lambda item: item.key)\n        book.replacements[symbol] = transfer.incumbent', count=1)
replace('uquant/portfolio/pipeline.py', '        book.account.replacement_tenure[transfer] = 0', '        transfer.consume(book.account)', count=1)
replace('uquant/portfolio/pipeline.py', 'and account.candidate_tenure.get(\n                   f"ordinary_repair_origin:{order.order_id}:{order.event_id}") == 1', 'and repair_origin_recorded(account, order.order_id, order.event_id)', count=1)
replace('uquant/portfolio/pipeline.py', '        book.account.candidate_tenure.pop("ordinary_repair_capital_active", None)\n        for key in list(book.account.candidate_tenure):\n            if key.startswith("ordinary_repair_origin:"):\n                book.account.candidate_tenure.pop(key)', '        clear_repair_origins(book.account)', count=1)
replace('uquant/portfolio/strategic/rearm.py', 'from __future__ import annotations\n', 'from __future__ import annotations\n\nfrom ...models.ordinary_state import record_repair_origin\n', count=1)
replace('uquant/portfolio/strategic/rearm.py', '    account.candidate_tenure["ordinary_repair_capital_active"] = 1\n    account.candidate_tenure[f"ordinary_repair_origin:{order.order_id}:{order.event_id}"] = 1', '    record_repair_origin(account, order.order_id, order.event_id)', count=1)
replace('uquant/portfolio/allocator.py', '        account.strategic_qualification = deepcopy(strategy_account.strategic_qualification)\n        for key, value in strategy_account.replacement_tenure.items():\n            if key.startswith(("strategic_qualification:", "strategic_eligibility:", "lifecycle_exit:", "pullback_exit:")):\n                account.replacement_tenure[key] = value\n        for key, value in strategy_account.candidate_tenure.items():\n            if key.startswith(("lifecycle_exit_session:", "pullback_exit:")):\n                account.candidate_tenure[key] = value\n        for event in strategy_account.lifecycle_events[len(account.lifecycle_events):]:\n            if event.get("event") == GRADUATION:\n                account.lifecycle_events.append(deepcopy(event))\n        for key in (\n            "strategic_cohort_qualification",\n            "strategic_long_cycle_open",\n            "strategic_eligibility_session",\n            "strategic_repair_observed_session",\n        ):\n            if key in strategy_account.candidate_tenure:\n                account.candidate_tenure[key] = strategy_account.candidate_tenure[key]\n        if account.strategic_qualification.candidate_symbol:\n            account.strategic_qualification.deployment_blocked = True\n            account.strategic_qualification.deployment_block_reason = "freeze_new_risk"\n', '        commit_frozen_observations(account, strategy_account)\n', count=1)
replace('uquant/portfolio/allocator.py', 'from ..models.ordinary_entry import GRADUATION\n', 'from .freeze import commit_frozen_observations\n', count=1)
replace('uquant/portfolio/freeze.py', 'from copy import deepcopy\n', 'from copy import deepcopy\n\nfrom ..models.ordinary_entry import GRADUATION\n', count=1)
write("uquant/portfolio/freeze.py", (ROOT/"uquant/portfolio/freeze.py").read_text() + '\n\ndef commit_frozen_observations(account: AccountState, strategy_account: AccountState) -> None:\n    """Commit only qualification, monotonic exits and graduation while frozen."""\n    account.strategic_qualification = deepcopy(strategy_account.strategic_qualification)\n    for key, value in strategy_account.replacement_tenure.items():\n        if key.startswith(("strategic_qualification:", "strategic_eligibility:", "lifecycle_exit:", "pullback_exit:")):\n            account.replacement_tenure[key] = value\n    for key, value in strategy_account.candidate_tenure.items():\n        if key.startswith(("lifecycle_exit_session:", "pullback_exit:")):\n            account.candidate_tenure[key] = value\n    for event in strategy_account.lifecycle_events[len(account.lifecycle_events):]:\n        if event.get("event") == GRADUATION:\n            account.lifecycle_events.append(deepcopy(event))\n    for key in (\n        "strategic_cohort_qualification",\n        "strategic_long_cycle_open",\n        "strategic_eligibility_session",\n        "strategic_repair_observed_session",\n    ):\n        if key in strategy_account.candidate_tenure:\n            account.candidate_tenure[key] = strategy_account.candidate_tenure[key]\n    if account.strategic_qualification.candidate_symbol:\n        account.strategic_qualification.deployment_blocked = True\n        account.strategic_qualification.deployment_block_reason = "freeze_new_risk"\n')

# Register the new production dependency in every surface containing its caller.
path = "benchmarks/source_surface_registry.json"
payload = json.loads((ROOT/path).read_text())
for surface in payload["surfaces"]:
    if "uquant/portfolio/pipeline.py" in surface["source_paths"] or "uquant/portfolio/strategic/rearm.py" in surface["source_paths"]:
        surface["source_paths"] = sorted(set(surface["source_paths"]) | {"uquant/models/ordinary_state.py"})
unsigned = {k: v for k,v in payload.items() if k != "canonical_sha256"}
payload["canonical_sha256"] = hashlib.sha256(json.dumps(unsigned, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False).encode()).hexdigest()
write(path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
